# Generated by Django 2.1.7 on 2019-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGFan', '0002_auto_20190317_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgmovies',
            name='release_date',
            field=models.IntegerField(default=50, verbose_name=50),
            preserve_default=False,
        ),
    ]
