# Generated by Django 2.1.7 on 2019-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGFan', '0003_sgmovies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgmovies',
            name='release_date',
            field=models.IntegerField(default=0),
        ),
    ]
