# Generated by Django 2.1.7 on 2019-03-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGFan', '0005_auto_20190317_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgmovies',
            options={'ordering': ['-title', '-image']},
        ),
    ]
