# Generated by Django 2.1.7 on 2019-03-21 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGFan', '0007_auto_20190317_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgmovies',
            options={},
        ),
        migrations.AddField(
            model_name='sgmovies',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
